SEED_EXAMS = [
    {
        "name": "UPSC Civil Services Examination",
        "conducting_org": "Union Public Service Commission (UPSC)",
        "description": "The Civil Services Examination (CSE) is a national competitive examination in India conducted by the Union Public Service Commission for recruitment to various Civil Services of the Government of India, including the Indian Administrative Service (IAS), Indian Foreign Service (IFS), and Indian Police Service (IPS).",
        "level": "Graduate",
        "eligibility": "Bachelor's degree from a recognized university. Age limit: 21 to 32 years.",
        "application_start_date": "2026-02-01",
        "last_date": "2026-03-05",
        "exam_date": "2026-05-26",
        "application_fee": "Rs. 100 (Female/SC/ST/PwBD are exempted)",
        "mode": "Offline (Pen & Paper)",
        "category": "Government Exams",
        "official_link": "https://upsc.gov.in",
        "syllabus_link": "https://upsc.gov.in/examinations/syllabus",
        "papers_link": "https://upsc.gov.in/examinations/previous-question-papers",
        "notification_pdf": "https://upsc.gov.in/sites/default/files/Notification-CSM-2026.pdf"
    },
    {
        "name": "JEE Advanced",
        "conducting_org": "Joint Admission Board (JAB)",
        "description": "Joint Entrance Examination - Advanced is an academic examination held annually in India. It is conducted by one of the seven zonal IITs under the guidance of the Joint Admission Board. It is used as the sole admission test by the 23 Indian Institutes of Technology (IITs).",
        "level": "12th",
        "eligibility": "Candidates must be among the top 2,50,000 successful candidates in JEE Main Paper 1. Physics, Chemistry, and Mathematics must be mandatory subjects in 12th.",
        "application_start_date": "2026-04-27",
        "last_date": "2026-05-07",
        "exam_date": "2026-06-01",
        "application_fee": "Rs. 3200 (Male General), Rs. 1600 (Female/SC/ST)",
        "mode": "Online (Computer Based Test)",
        "category": "Engineering Exams",
        "official_link": "https://jeeadv.ac.in",
        "syllabus_link": "https://jeeadv.ac.in/syllabus.html",
        "papers_link": "https://jeeadv.ac.in/past_question_papers.html",
        "notification_pdf": "https://jeeadv.ac.in/documents/information-brochure.pdf"
    },
    {
        "name": "JEE Main",
        "conducting_org": "National Testing Agency (NTA)",
        "description": "Joint Entrance Examination - Main is an all-India standardized computer-based test for admission to various technical undergraduate programs in engineering, architecture, and planning across India, specifically in NITs, IIITs, and CFTIs.",
        "level": "12th",
        "eligibility": "Passed 10+2 or equivalent exam with Physics, Mathematics, and one of Chemistry/Biology/Technical Vocational subjects.",
        "application_start_date": "2026-11-01",
        "last_date": "2026-12-04",
        "exam_date": "2026-01-24",
        "application_fee": "Rs. 1000 (Male Gen), Rs. 800 (Female Gen), Rs. 500 (SC/ST)",
        "mode": "Online (Computer Based Test)",
        "category": "Engineering Exams",
        "official_link": "https://jeemain.nta.ac.in",
        "syllabus_link": "https://jeemain.nta.ac.in/syllabus/",
        "papers_link": "https://jeemain.nta.ac.in/previous-years-question-papers/",
        "notification_pdf": "https://jeemain.nta.ac.in/information-bulletin/"
    },
    {
        "name": "NEET UG",
        "conducting_org": "National Testing Agency (NTA)",
        "description": "The National Eligibility cum Entrance Test (Undergraduate) is an all-India pre-medical entrance test for students who wish to pursue undergraduate medical (MBBS), dental (BDS), and equivalent AYUSH courses in government and private institutions.",
        "level": "12th",
        "eligibility": "Passed 10+2 with Physics, Chemistry, Biology/Biotechnology, and English as core subjects. Minimum age limit is 17 years.",
        "application_start_date": "2026-02-09",
        "last_date": "2026-03-16",
        "exam_date": "2026-05-03",
        "application_fee": "Rs. 1700 (General), Rs. 1600 (OBC-NCL), Rs. 1000 (SC/ST/PwBD)",
        "mode": "Offline (Pen & Paper)",
        "category": "Medical Exams",
        "official_link": "https://neet.nta.nic.in",
        "syllabus_link": "https://neet.nta.nic.in/syllabus/",
        "papers_link": "https://neet.nta.nic.in/question-papers/",
        "notification_pdf": "https://neet.nta.nic.in/documents/information-bulletin.pdf"
    },
    {
        "name": "GATE (Graduate Aptitude Test in Engineering)",
        "conducting_org": "Indian Institute of Science (IISc) & IITs",
        "description": "An examination that primarily tests the comprehensive understanding of various undergraduate subjects in engineering and science for admission into Master's programs and recruitment by Public Sector Undertakings (PSUs).",
        "level": "UG",
        "eligibility": "Currently studying in the 3rd or higher years of any undergraduate degree program, or has completed a government-approved degree in Engineering/Technology/Architecture/Science/Commerce/Arts.",
        "application_start_date": "2026-08-30",
        "last_date": "2026-10-12",
        "exam_date": "2027-02-06",
        "application_fee": "Rs. 1800 (General), Rs. 900 (Female/SC/ST)",
        "mode": "Online (Computer Based Test)",
        "category": "Engineering Exams",
        "official_link": "https://gate.iisc.ac.in",
        "syllabus_link": "https://gate.iisc.ac.in/syllabus/",
        "papers_link": "https://gate.iisc.ac.in/previous-question-papers/",
        "notification_pdf": "https://gate.iisc.ac.in/brochure/"
    },
    {
        "name": "IBPS PO",
        "conducting_org": "Institute of Banking Personnel Selection (IBPS)",
        "description": "A national-level exam conducted to recruit Probationary Officers (PO) / Management Trainees in participating public sector banks across India.",
        "level": "Graduate",
        "eligibility": "A degree (Graduation) in any discipline from a University recognized by the Government of India. Age: 20 to 30 years.",
        "application_start_date": "2026-08-01",
        "last_date": "2026-08-22",
        "exam_date": "2026-10-15",
        "application_fee": "Rs. 850 (General/OBC), Rs. 175 (SC/ST/PwBD)",
        "mode": "Online (Computer Based Test)",
        "category": "Banking Exams",
        "official_link": "https://ibps.in",
        "syllabus_link": "https://ibps.in/syllabus-po",
        "papers_link": "https://ibps.in/previous-papers",
        "notification_pdf": "https://ibps.in/crp-po-mt-notification"
    },
    {
        "name": "SSC CHSL (Combined Higher Secondary Level)",
        "conducting_org": "Staff Selection Commission (SSC)",
        "description": "Conducted for recruitment to posts of Lower Divisional Clerk (LDC), Junior Secretariat Assistant (JSA), Postal Assistant (PA), Sorting Assistant (SA), and Data Entry Operator (DEO) in various Ministries, Departments, and Offices of the Government of India.",
        "level": "12th",
        "eligibility": "Must have passed 12th Standard or equivalent examination from a recognized Board or University. Age limit: 18 to 27 years.",
        "application_start_date": "2026-04-02",
        "last_date": "2026-05-02",
        "exam_date": "2026-07-01",
        "application_fee": "Rs. 100 (Women/SC/ST/PwD/ESM are exempted)",
        "mode": "Online (Computer Based Test)",
        "category": "Government Exams",
        "official_link": "https://ssc.gov.in",
        "syllabus_link": "https://ssc.gov.in/syllabus/chsl",
        "papers_link": "https://ssc.gov.in/previous-years-questions",
        "notification_pdf": "https://ssc.gov.in/notification/chsl-2026"
    },
    {
        "name": "SSC MTS (Multi-Tasking Staff)",
        "conducting_org": "Staff Selection Commission (SSC)",
        "description": "Conducted to recruit Group C non-gazetted, non-ministerial posts in various ministries, departments, and offices of the Government of India.",
        "level": "10th",
        "eligibility": "Must have passed Matriculation (10th Class) Examination or equivalent from a recognized board. Age limit: 18 to 25/27 years.",
        "application_start_date": "2026-06-27",
        "last_date": "2026-07-31",
        "exam_date": "2026-10-12",
        "application_fee": "Rs. 100 (Women/SC/ST/PwD/ESM are exempted)",
        "mode": "Online (Computer Based Test)",
        "category": "Government Exams",
        "official_link": "https://ssc.gov.in",
        "syllabus_link": "https://ssc.gov.in/syllabus/mts",
        "papers_link": "https://ssc.gov.in/previous-years-questions",
        "notification_pdf": "https://ssc.gov.in/notification/mts-2026"
    },
    {
        "name": "Common University Entrance Test (CUET UG)",
        "conducting_org": "National Testing Agency (NTA)",
        "description": "Common University Entrance Test is an all-India test organized by NTA for admission to various Under Graduate courses in central, state, private, and deemed universities across India.",
        "level": "12th",
        "eligibility": "Passed 12th standard exam or appearing in 2026. No age limit specified by NTA, but subject to individual university rules.",
        "application_start_date": "2026-02-27",
        "last_date": "2026-04-05",
        "exam_date": "2026-05-15",
        "application_fee": "Based on number of subjects chosen (typical: Rs. 750 to Rs. 1500)",
        "mode": "Hybrid (Pen & Paper and Computer Based Test)",
        "category": "College Entrance Exams",
        "official_link": "https://exams.nta.ac.in/CUET-UG/",
        "syllabus_link": "https://exams.nta.ac.in/CUET-UG/syllabus.html",
        "papers_link": "https://exams.nta.ac.in/CUET-UG/past-papers.html",
        "notification_pdf": "https://exams.nta.ac.in/CUET-UG/docs/CUET-UG-Info-Bulletin.pdf"
    }
]
